
## Using Promises with Then() and Catch() :cactus: &nbsp; :trollface:
- The __then()__ and __catch()__ methods are used to handle the results of __Promises__ once they have finished pending.
- The __then()__ method is used to handle __resolved__ Promises.
- The __catch()__ method is used to handle __rejected__ Promises.
- Both of these methods use callback functions.
- The callback functions should each have one argument representing the Promise result.

<kbd>Promise w/Then()_Catch()</kbd>     :mushroom:       
![](/images/Promise.png)


```
    var promise = new Promise(function() {
      
      //do stuff
     
     var isSuccessful = true;
      setTimeout(function() {                 //asynchronous process after 5 secs
        if(isSuccessful) {                    //if everything went ok
            resolve('success');
        }//if successful
        else {                                //if something went wrong
            reject(Error('failure'));
        }//else
      
      },5000);
    
    
    }); //promise
    
```


<kbd>promise status changes from pending to resolved after 5 seconds</kbd> &nbsp; :calling:
```
    
    promise.then(function(val) {      //val represents the fulfillment value
        
        console.log(val);             //logs 'success' since promise resolved
        
    }).catch(function(val) {          //val represents the rejection value
    
        console.log(val);             //doesnt happened since promise never rejected
    
    });

```

### Using Promises with Then( onSuccess, onFailure) &nbsp;  :black_nib:  &nbsp; :honey_pot:
The __then()__ method can be called with a success callback and a failure callback, as an alternative to using the __then()__ and __catch()__ methods.

> then() method used with a success and failure callback to handle promise results:

```
        promise.then(function(val) {    //success callback
        
            console.log(val);
        
        }, function(val) {      //rejection callback
        
            console.log(val);
        
        });
```

### Ex Promise :cactus:
- Here we have a promise __constructor__
- It takes 2 values: the __resolve__ and __reject__ methods
- Resolve method goes from __pending__ to __fulfill__ values
- Reject method goes from __pending__ to __rejected__ values
- Sets a timeout for 5000 milliseconds
- Set a variable equal to a random decimal
- If var __above .5__ is __resolved__ or __rejected__ if __less__ than ( __promise has been created now__)  :boom:
- Then extract promise result using then and catch methods



```     
        var promise = new Promise(function(resolve,reject) {
            setTimeout(function() {
                var val = Math.random();
                if(val > .5) {
                    resolve(val);
                }//if more
                else {
                    reject(val);
                }//else
            },5000);
        });
```
Extracting promise results:

```
    promise.then(function(dat) {
        console.log('success: ' + dat);
    }).catch(function(err) {
        console.log('error ' + err);
    });

```
result:

```
    => "success: 0.8337446307053523"
```








:100:









